name: SonarQube Analysis

on:
  push:
    paths:
      - .github/workflows/cloud.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: |
            ${{ runner.os }}-sonar-cache

      - name: Build project
        run: |
          make clean
          make

      - name: Prepare Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir bldwrapper-output make clean
          build-wrapper-linux-x86-64 --out-dir bldwrapper-output make

      - name: Run SonarQube Scanner
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my:cpp_project \
            -Dsonar.organization=my-github-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.cfamily.build-wrapper-output=bldwrapper-output \
            -Dsonar.branch.name=${{ github.ref_name }}
