name: SonarQube Analysis

on:
  push:
    paths:
      - .github/workflows/cloud.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      # - name: Cache SonarQube packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.sonar/cache
      #     key: ${{ runner.os }}-sonar-cache
      #     restore-keys: |
      #       ${{ runner.os }}-sonar-cache

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Prepare Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir bldwrapper-output make clean all

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="bldwrapper-output/compile_commands.json" -Dsonar.branch.name=${{ github.ref_name }}

