name: Scan

on:
  push:
    paths:
     - .github/workflows/scan.yml
     
  workflow_dispatch:

jobs:
  openvas-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: github/codeql-action/init@v3
      with:
        languages: "c-cpp"
        build-mode: autobuild

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v3
